# Makefile for jl_lib projects.

ifneq ($(shell echo $(JLL_HOME)), "")
 include $(shell echo $(JLL_HOME))/ProjectMakefile.mk
else
 $(error "You need to set enviroment variable JLL_HOME to the jl_lib directory")
endif
